# Quick Fix Workflow
# Streamlined workflow for small fixes (<1 hour)
#
# Documentation: @.claude/workflows/documentation/BUG-WORKFLOW.md

name: quick-fix
description: Fast-track workflow for minor fixes and improvements
trigger: "bug_fix | hotfix | small_change | typo"

# Expected duration: <1 hour
# Parallelization: None (single-track)

prerequisites:
  - issue_clearly_defined
  - scope_is_small
  - no_architectural_changes

# Criteria for quick-fix eligibility
eligibility:
  max_files_changed: 3
  max_lines_changed: 100
  no_new_dependencies: true
  no_schema_changes: true
  no_api_contract_changes: true

steps:
  - id: assess
    agent: senior-dev
    type: assess_fix
    description: "Assess fix scope and approach"
    input:
      context_refs:
        - "Issue description or bug report"
    output:
      assessment:
        - estimated_scope: "small | medium | large"
        - files_affected: []
        - approach: "description"
    decision:
      small: implement
      medium_or_large: escalate_to_story

  - id: implement
    agent: senior-dev
    type: fix_with_tests
    description: "Implement fix with corresponding tests"
    input:
      context_refs:
        - "Affected source files"
        - "Related test files"
    output:
      deliverables:
        - "Fixed source files"
        - "Updated/new tests"
    checkpoint:
      - "Fix addresses root cause"
      - "Tests cover the fix"
      - "All tests pass"
    next: review

  - id: review
    agent: code-reviewer
    type: quick_review
    description: "Fast review for small changes"
    input:
      context_refs:
        - "Changed files (diff)"
    decision:
      approved: complete
      request_changes: return_to_implement
    checkpoint:
      - "No security issues"
      - "Tests adequate"
      - "Code quality OK"

  - id: complete
    type: fix_complete
    summary: "Fix implemented and reviewed"
    actions:
      - "Update issue status"
      - "Create commit"

  - id: escalate_to_story
    type: escalation
    description: "Fix is too large for quick-fix workflow"
    action: "Create story, route to story-delivery workflow"
    next_workflow: "engineering/story-delivery.yaml"

# Shortcuts for common fixes
shortcuts:
  typo_fix:
    skip_to: implement
    skip_review: false

  config_change:
    skip_to: implement
    require_review: true

# Error handling
on_error:
  log_to: "@.claude/logs/workflows/"
  retry_count: 0
  escalate_to: user
