#!/bin/bash
# Project Initialization Script
# Initializes a new project with the Agent Methodology Pack
#
# Usage: bash scripts/init-project.sh <project-name> [--skip-git]
# Example: bash scripts/init-project.sh my-awesome-app
#
# Options:
#   --skip-git    Skip git initialization
#
# Author: Agent Methodology Pack
# Version: 1.0

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Default values
PROJECT_NAME=""
SKIP_GIT=false

# Parse arguments
if [ $# -eq 0 ]; then
    echo ""
    echo -e "${RED}Error: Project name required${NC}"
    echo ""
    echo "Usage: bash scripts/init-project.sh <project-name> [--skip-git]"
    echo ""
    echo "Example:"
    echo "  bash scripts/init-project.sh my-awesome-app"
    echo ""
    exit 1
fi

PROJECT_NAME="$1"

if [[ "$2" == "--skip-git" ]]; then
    SKIP_GIT=true
fi

# Helper functions
print_header() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_step() {
    echo -e "${CYAN}▶ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ️  $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

# Check if running from the methodology pack directory
check_location() {
    if [ ! -d ".claude" ] || [ ! -d "templates" ]; then
        echo ""
        echo -e "${RED}Error: This script must be run from the agent-methodology-pack directory${NC}"
        echo ""
        echo "Please cd into the agent-methodology-pack directory and try again."
        echo ""
        exit 1
    fi
}

# Main script
main() {
    check_location

    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║          PROJECT INITIALIZATION - METHODOLOGY PACK         ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"

    echo ""
    echo -e "${MAGENTA}Initializing project: ${PROJECT_NAME}${NC}"
    echo ""

    # ============================================================
    # 1. CREATE CLAUDE.md FROM TEMPLATE
    # ============================================================
    print_header "1. Creating CLAUDE.md"

    if [ -f "templates/CLAUDE.md.template" ]; then
        print_step "Generating CLAUDE.md from template..."

        # Replace placeholder with project name
        sed "s/{PROJECT_NAME}/${PROJECT_NAME}/g" templates/CLAUDE.md.template > CLAUDE.md

        # Add current date
        CURRENT_DATE=$(date '+%Y-%m-%d')
        sed -i.bak "s/{DATE}/${CURRENT_DATE}/g" CLAUDE.md 2>/dev/null || true

        print_success "CLAUDE.md created"

        # Check line count
        LINES=$(wc -l < CLAUDE.md | tr -d ' ')
        if [ "$LINES" -le 70 ]; then
            print_success "CLAUDE.md is within 70-line limit ($LINES lines)"
        else
            print_warning "CLAUDE.md exceeds 70-line limit ($LINES lines) - consider trimming"
        fi
    else
        print_warning "Template not found - creating minimal CLAUDE.md"

        cat > CLAUDE.md << EOF
# ${PROJECT_NAME}

## Project Overview
[Describe your project]

## Tech Stack
- Framework: [Your framework]
- Language: [Your language]

## Current Phase
Phase: Planning
Sprint: 1

## Key Files
- @PROJECT-STATE.md - Current sprint status
- @.claude/agents/ORCHESTRATOR.md - Agent orchestration
- @docs/2-MANAGEMENT/backlog.md - Product backlog

## Instructions
[Your specific instructions for Claude]

---
*Auto-generated by init-project.sh*
EOF

        print_success "Minimal CLAUDE.md created"
    fi

    # ============================================================
    # 2. CREATE PROJECT-STATE.md FROM TEMPLATE
    # ============================================================
    print_header "2. Creating PROJECT-STATE.md"

    if [ -f "templates/PROJECT-STATE.md.template" ]; then
        print_step "Copying PROJECT-STATE.md template..."

        cp templates/PROJECT-STATE.md.template PROJECT-STATE.md

        # Replace placeholders
        sed -i.bak "s/{PROJECT_NAME}/${PROJECT_NAME}/g" PROJECT-STATE.md 2>/dev/null || true
        sed -i.bak "s/{DATE}/${CURRENT_DATE}/g" PROJECT-STATE.md 2>/dev/null || true

        print_success "PROJECT-STATE.md created"
    else
        print_warning "Template not found - creating minimal PROJECT-STATE.md"

        cat > PROJECT-STATE.md << EOF
# ${PROJECT_NAME} - Project State

## Current Sprint
Sprint: 1
Start Date: ${CURRENT_DATE}
Sprint Goal: Initial setup and planning

## Active Work
- Setting up project structure
- Initial planning

## Blockers
None

## Recent Updates
- ${CURRENT_DATE}: Project initialized

---
*Auto-generated by init-project.sh*
EOF

        print_success "Minimal PROJECT-STATE.md created"
    fi

    # ============================================================
    # 3. VERIFY FOLDER STRUCTURE
    # ============================================================
    print_header "3. Verifying Folder Structure"

    REQUIRED_DIRS=(
        ".claude"
        ".claude/agents"
        ".claude/agents/planning"
        ".claude/agents/development"
        ".claude/agents/quality"
        ".claude/patterns"
        ".claude/state"
        ".claude/workflows"
        "docs"
        "docs/1-BASELINE"
        "docs/2-MANAGEMENT"
        "docs/2-MANAGEMENT/epics"
        "docs/2-MANAGEMENT/epics/current"
        "docs/2-MANAGEMENT/sprints"
        "docs/3-ARCHITECTURE"
        "docs/4-DEVELOPMENT"
        "docs/5-ARCHIVE"
        "scripts"
        "templates"
    )

    MISSING_DIRS=0

    for dir in "${REQUIRED_DIRS[@]}"; do
        if [ ! -d "$dir" ]; then
            print_step "Creating $dir..."
            mkdir -p "$dir"
            ((MISSING_DIRS++))
        fi
    done

    if [ $MISSING_DIRS -eq 0 ]; then
        print_success "All required directories exist"
    else
        print_success "Created $MISSING_DIRS missing directories"
    fi

    # ============================================================
    # 4. INITIALIZE STATE FILES (IF MISSING)
    # ============================================================
    print_header "4. Checking State Files"

    # Create empty state files if they don't exist
    STATE_FILES=(
        ".claude/state/AGENT-STATE.md"
        ".claude/state/AGENT-MEMORY.md"
        ".claude/state/TASK-QUEUE.md"
        ".claude/state/HANDOFFS.md"
        ".claude/state/DECISION-LOG.md"
        ".claude/state/DEPENDENCIES.md"
        ".claude/state/METRICS.md"
    )

    CREATED_FILES=0

    for state_file in "${STATE_FILES[@]}"; do
        if [ ! -f "$state_file" ]; then
            print_step "Creating $(basename "$state_file")..."

            # Create header based on file name
            filename=$(basename "$state_file" .md)
            cat > "$state_file" << EOF
# ${filename}

*Initialized: ${CURRENT_DATE}*

<!-- This file will be populated during project execution -->

EOF
            ((CREATED_FILES++))
        fi
    done

    if [ $CREATED_FILES -eq 0 ]; then
        print_success "All state files exist"
    else
        print_success "Created $CREATED_FILES state files"
    fi

    # ============================================================
    # 5. GIT INITIALIZATION
    # ============================================================
    print_header "5. Git Repository"

    if [ "$SKIP_GIT" = true ]; then
        print_info "Skipping git initialization (--skip-git flag)"
    else
        if [ -d ".git" ]; then
            print_info "Git repository already initialized"
        else
            print_step "Initializing git repository..."
            git init
            print_success "Git initialized"

            # Create .gitignore if it doesn't exist
            if [ ! -f ".gitignore" ]; then
                print_step "Creating .gitignore..."

                cat > .gitignore << EOF
# OS Files
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo

# Backup files
*.backup
*.bak

# Temporary files
*.tmp
~*

# Node modules (if using JS/TS)
node_modules/

# Python (if using Python)
__pycache__/
*.pyc
.venv/
venv/

# Environment files
.env
.env.local

EOF
                print_success ".gitignore created"
            fi

            # Create initial commit (optional)
            print_step "Creating initial commit..."
            git add .
            git commit -m "Initial commit: Project setup with Agent Methodology Pack

Project: ${PROJECT_NAME}
Date: ${CURRENT_DATE}

Generated with init-project.sh from agent-methodology-pack" || print_warning "Could not create initial commit"
        fi
    fi

    # ============================================================
    # 6. VALIDATE INSTALLATION
    # ============================================================
    print_header "6. Validating Installation"

    print_step "Running validation script..."
    echo ""

    if [ -f "scripts/validate-docs.sh" ]; then
        bash scripts/validate-docs.sh || print_warning "Validation found some issues - review output above"
    else
        print_warning "Validation script not found - skipping"
    fi

    # ============================================================
    # 7. GENERATE QUICK START GUIDE
    # ============================================================
    print_header "7. Generating Quick Start Guide"

    QUICKSTART_FILE="QUICK-START-${PROJECT_NAME}.md"

    cat > "$QUICKSTART_FILE" << EOF
# Quick Start Guide: ${PROJECT_NAME}

Generated: ${CURRENT_DATE}

## 🚀 Getting Started

### 1. Review Core Files
- [ ] Read and customize \`CLAUDE.md\`
- [ ] Review \`PROJECT-STATE.md\`
- [ ] Check \`.claude/agents/ORCHESTRATOR.md\`

### 2. Define Your Project
- [ ] Add project description to CLAUDE.md
- [ ] List your tech stack
- [ ] Define initial goals

### 3. Start Planning
Run the ORCHESTRATOR agent to begin:

\`\`\`
I need help with: [describe your first task]

Context:
- @CLAUDE.md
- @PROJECT-STATE.md
- @.claude/agents/ORCHESTRATOR.md
\`\`\`

### 4. First Sprint Setup
1. Run SCRUM-MASTER for sprint planning
2. Create epics with PM-AGENT
3. Break down into stories
4. Start development

## 📁 Project Structure

\`\`\`
${PROJECT_NAME}/
├── CLAUDE.md              # Main project file (always loaded)
├── PROJECT-STATE.md       # Current sprint status
├── .claude/
│   ├── agents/            # Agent definitions
│   ├── patterns/          # Development patterns
│   ├── state/             # Runtime state
│   └── workflows/         # Process workflows
├── docs/
│   ├── 1-BASELINE/        # Requirements & vision
│   ├── 2-MANAGEMENT/      # Epics, stories, sprints
│   ├── 3-ARCHITECTURE/    # Technical architecture
│   ├── 4-DEVELOPMENT/     # Implementation docs
│   └── 5-ARCHIVE/         # Completed work
├── scripts/               # Automation scripts
└── templates/             # Document templates
\`\`\`

## 🤖 Available Agents

### Planning Phase
- **PRODUCT-OWNER**: Define vision and requirements
- **PM-AGENT**: Create epics and stories
- **SCRUM-MASTER**: Sprint planning and management
- **ARCHITECT-AGENT**: Technical architecture
- **UX-DESIGNER**: User experience design
- **RESEARCH-AGENT**: Technical research

### Development Phase
- **FRONTEND-DEV**: UI/UX implementation
- **BACKEND-DEV**: Server-side logic
- **SENIOR-DEV**: Integration & complex logic
- **TEST-ENGINEER**: Testing strategy

### Quality Phase
- **QA-AGENT**: Quality assurance
- **CODE-REVIEWER**: Code review
- **TECH-WRITER**: Documentation

## 🛠️ Useful Commands

### Validate Project Structure
\`\`\`bash
bash scripts/validate-docs.sh
\`\`\`

### Check Token Usage
\`\`\`bash
bash scripts/token-counter.sh
bash scripts/token-counter.sh --verbose
\`\`\`

### Sprint Transition
\`\`\`bash
bash scripts/sprint-transition.sh 1 2
\`\`\`

## 📚 Next Steps

1. **Define Requirements**
   - Use PRODUCT-OWNER to create vision doc
   - Document user needs in docs/1-BASELINE/

2. **Create First Epic**
   - Use PM-AGENT to break down work
   - Save to docs/2-MANAGEMENT/epics/current/

3. **Plan Sprint 1**
   - Use SCRUM-MASTER for planning
   - Set sprint goal in PROJECT-STATE.md

4. **Start Development**
   - Use development agents for implementation
   - Follow TDD with TEST-ENGINEER

5. **Quality Assurance**
   - Use QA-AGENT for testing
   - CODE-REVIEWER for code review

## 🔗 Important Links

- Orchestrator: \`.claude/agents/ORCHESTRATOR.md\`
- Workflows: \`.claude/workflows/\`
- Patterns: \`.claude/patterns/\`
- Context Budget: \`.claude/CONTEXT-BUDGET.md\`

---

*Generated by init-project.sh*
EOF

    print_success "Quick start guide created: $QUICKSTART_FILE"

    # ============================================================
    # COMPLETION SUMMARY
    # ============================================================
    print_header "INITIALIZATION COMPLETE"

    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  🎉 PROJECT '${PROJECT_NAME}' SUCCESSFULLY INITIALIZED! 🎉  ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    echo -e "${CYAN}Created Files:${NC}"
    echo -e "  ✓ CLAUDE.md"
    echo -e "  ✓ PROJECT-STATE.md"
    echo -e "  ✓ $QUICKSTART_FILE"
    if [ "$SKIP_GIT" = false ] && [ -f ".gitignore" ]; then
        echo -e "  ✓ .gitignore"
    fi
    echo ""

    echo -e "${CYAN}Project Structure:${NC}"
    echo -e "  ✓ All required directories created"
    echo -e "  ✓ State files initialized"
    echo -e "  ✓ Agent definitions ready"
    echo ""

    if [ "$SKIP_GIT" = false ]; then
        echo -e "${CYAN}Git Repository:${NC}"
        echo -e "  ✓ Initialized"
        echo -e "  ✓ Initial commit created"
        echo ""
    fi

    print_header "NEXT STEPS"

    echo ""
    echo -e "${YELLOW}1. Customize your project:${NC}"
    echo -e "   - Edit CLAUDE.md with project details"
    echo -e "   - Update PROJECT-STATE.md with sprint info"
    echo ""
    echo -e "${YELLOW}2. Read the quick start guide:${NC}"
    echo -e "   - Open $QUICKSTART_FILE"
    echo ""
    echo -e "${YELLOW}3. Start with the ORCHESTRATOR:${NC}"
    echo -e "   - Load @.claude/agents/ORCHESTRATOR.md"
    echo -e "   - Describe your first task"
    echo ""
    echo -e "${YELLOW}4. Follow the workflow:${NC}"
    echo -e "   - Planning: .claude/workflows/PLANNING-FLOW.md"
    echo -e "   - Development: .claude/workflows/DEVELOPMENT-FLOW.md"
    echo ""
    echo -e "${YELLOW}5. State & Commit sync (auto-runs after each phase):${NC}"
    echo -e "   - bash scripts/sync-state.sh              # Just sync state"
    echo -e "   - bash scripts/sync-state.sh --commit     # Sync + commit"
    echo -e "   - bash scripts/sync-state.sh --phase discovery --commit"
    echo ""

    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║                HAPPY BUILDING WITH AGENTS! 🤖              ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

# Run main function
main
