#!/bin/bash
# Sprint Transition Script
# Automates sprint closure and new sprint initialization
#
# Usage: bash scripts/sprint-transition.sh <old_sprint> <new_sprint>
# Example: bash scripts/sprint-transition.sh 1 2
#
# Author: Agent Methodology Pack
# Version: 1.0

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Check arguments
if [ $# -lt 2 ]; then
    echo ""
    echo -e "${RED}Error: Missing arguments${NC}"
    echo ""
    echo "Usage: bash scripts/sprint-transition.sh <old_sprint> <new_sprint>"
    echo ""
    echo "Example:"
    echo "  bash scripts/sprint-transition.sh 1 2"
    echo ""
    exit 1
fi

OLD_SPRINT="$1"
NEW_SPRINT="$2"

# Helper functions
print_header() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_step() {
    echo -e "${CYAN}▶ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ️  $1${NC}"
}

# Main script
main() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║              SPRINT TRANSITION AUTOMATION                  ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"

    echo ""
    echo -e "${MAGENTA}Transitioning from Sprint $OLD_SPRINT to Sprint $NEW_SPRINT${NC}"
    echo ""

    # ============================================================
    # 1. ARCHIVE COMPLETED EPICS
    # ============================================================
    print_header "1. Archiving Completed Work"

    ARCHIVE_DIR="docs/5-ARCHIVE/sprint-${OLD_SPRINT}"
    CURRENT_EPICS_DIR="docs/2-MANAGEMENT/epics/current"

    print_step "Creating archive directory..."
    mkdir -p "$ARCHIVE_DIR/epics"
    mkdir -p "$ARCHIVE_DIR/metrics"
    print_success "Archive directory created: $ARCHIVE_DIR"

    # Archive completed epics
    if [ -d "$CURRENT_EPICS_DIR" ]; then
        print_step "Archiving completed epics..."

        ARCHIVED_COUNT=0
        for epic_file in "$CURRENT_EPICS_DIR"/epic-*.md; do
            if [ -f "$epic_file" ]; then
                # Check if epic is completed (you can customize this check)
                if grep -q "Status: Completed" "$epic_file" 2>/dev/null; then
                    cp "$epic_file" "$ARCHIVE_DIR/epics/"
                    print_success "Archived: $(basename "$epic_file")"
                    ((ARCHIVED_COUNT++))
                fi
            fi
        done

        if [ $ARCHIVED_COUNT -eq 0 ]; then
            print_info "No completed epics found to archive"
        else
            print_success "Archived $ARCHIVED_COUNT epic(s)"
        fi
    fi

    # ============================================================
    # 2. GENERATE SPRINT SUMMARY
    # ============================================================
    print_header "2. Generating Sprint Summary"

    SUMMARY_FILE="$ARCHIVE_DIR/sprint-${OLD_SPRINT}-summary.md"
    DATE=$(date '+%Y-%m-%d')

    print_step "Creating sprint summary..."

    cat > "$SUMMARY_FILE" << EOF
# Sprint $OLD_SPRINT Summary
Generated: $DATE

## Overview
Sprint ${OLD_SPRINT} has been completed and archived.

## Metrics
<!-- Copy from METRICS.md -->

### Velocity
- Stories Completed: TBD
- Story Points: TBD
- Velocity: TBD

### Quality
- Tests Written: TBD
- Code Coverage: TBD
- Bugs Found: TBD
- Bugs Fixed: TBD

### Time
- Sprint Duration: TBD days
- Average Story Time: TBD

## Completed Epics
<!-- List archived epics -->
$(if [ $ARCHIVED_COUNT -gt 0 ]; then
    for epic_file in "$ARCHIVE_DIR/epics"/epic-*.md; do
        if [ -f "$epic_file" ]; then
            epic_name=$(basename "$epic_file" .md)
            echo "- $epic_name"
        fi
    done
else
    echo "- None"
fi)

## Key Achievements
- TBD

## Challenges & Learnings
- TBD

## Retrospective Notes
- TBD

## Technical Debt
<!-- Items to address in future sprints -->
- TBD

---

*This summary was auto-generated by sprint-transition.sh*
EOF

    print_success "Sprint summary created: $SUMMARY_FILE"

    # ============================================================
    # 3. COPY METRICS
    # ============================================================
    print_header "3. Saving Sprint Metrics"

    if [ -f ".claude/state/METRICS.md" ]; then
        print_step "Copying current metrics..."
        cp ".claude/state/METRICS.md" "$ARCHIVE_DIR/metrics/METRICS-sprint-${OLD_SPRINT}.md"
        print_success "Metrics saved to archive"
    else
        print_info "METRICS.md not found - skipping"
    fi

    # ============================================================
    # 4. UPDATE PROJECT-STATE
    # ============================================================
    print_header "4. Updating PROJECT-STATE.md"

    if [ -f "PROJECT-STATE.md" ]; then
        print_step "Updating current sprint reference..."

        # Create backup
        cp "PROJECT-STATE.md" "PROJECT-STATE.md.backup"

        # Update sprint number (if it exists in the file)
        sed -i.bak "s/Sprint: $OLD_SPRINT/Sprint: $NEW_SPRINT/g" "PROJECT-STATE.md" 2>/dev/null || true
        sed -i.bak "s/Current Sprint: $OLD_SPRINT/Current Sprint: $NEW_SPRINT/g" "PROJECT-STATE.md" 2>/dev/null || true

        print_success "PROJECT-STATE.md updated"
        print_info "Backup saved as PROJECT-STATE.md.backup"
    else
        print_info "PROJECT-STATE.md not found"
    fi

    # ============================================================
    # 5. CLEAN UP STATE FILES
    # ============================================================
    print_header "5. Preparing State Files for New Sprint"

    # Clean up completed tasks from TASK-QUEUE
    if [ -f ".claude/state/TASK-QUEUE.md" ]; then
        print_step "Archiving completed tasks..."

        # Save current task queue
        cp ".claude/state/TASK-QUEUE.md" "$ARCHIVE_DIR/TASK-QUEUE-sprint-${OLD_SPRINT}.md"

        # Note: Don't auto-delete completed tasks, just notify user
        print_info "Task queue archived. Review and clean manually if needed."
    fi

    # Archive handoffs
    if [ -f ".claude/state/HANDOFFS.md" ]; then
        cp ".claude/state/HANDOFFS.md" "$ARCHIVE_DIR/HANDOFFS-sprint-${OLD_SPRINT}.md"
        print_success "Handoffs archived"
    fi

    # Archive decision log
    if [ -f ".claude/state/DECISION-LOG.md" ]; then
        cp ".claude/state/DECISION-LOG.md" "$ARCHIVE_DIR/DECISION-LOG-sprint-${OLD_SPRINT}.md"
        print_success "Decision log archived"
    fi

    # ============================================================
    # 6. CREATE NEW SPRINT FOLDER
    # ============================================================
    print_header "6. Setting Up New Sprint"

    NEW_SPRINT_DIR="docs/2-MANAGEMENT/sprints/sprint-${NEW_SPRINT}"

    print_step "Creating sprint directory structure..."
    mkdir -p "$NEW_SPRINT_DIR/planning"
    mkdir -p "$NEW_SPRINT_DIR/retrospective"

    # Create sprint planning template
    cat > "$NEW_SPRINT_DIR/planning/sprint-${NEW_SPRINT}-plan.md" << EOF
# Sprint $NEW_SPRINT Planning
Date: $DATE

## Sprint Goal
<!-- Define the main objective for this sprint -->

## Capacity
- Team Size: TBD
- Sprint Duration: TBD weeks
- Available Story Points: TBD

## Selected Stories
<!-- Stories pulled from backlog -->

### High Priority
- [ ] TBD

### Medium Priority
- [ ] TBD

### Low Priority
- [ ] TBD

## Dependencies
<!-- External dependencies or blockers -->

## Notes
<!-- Additional planning notes -->

---
*Created by sprint-transition.sh*
EOF

    print_success "Sprint planning template created"

    # Create retrospective template
    cat > "$NEW_SPRINT_DIR/retrospective/template.md" << EOF
# Sprint $NEW_SPRINT Retrospective

## What Went Well
-

## What Could Be Improved
-

## Action Items
- [ ]

## Metrics Review
<!-- Reference metrics from METRICS.md -->

---
*Template created by sprint-transition.sh*
EOF

    print_success "Retrospective template created"

    # ============================================================
    # SUMMARY
    # ============================================================
    print_header "TRANSITION COMPLETE"

    echo ""
    echo -e "${GREEN}Sprint transition completed successfully!${NC}"
    echo ""
    echo -e "${CYAN}Archive Location:${NC} $ARCHIVE_DIR"
    echo -e "${CYAN}New Sprint Folder:${NC} $NEW_SPRINT_DIR"
    echo ""

    print_header "NEXT STEPS"

    echo ""
    echo -e "${YELLOW}1. Review sprint summary and add details:${NC}"
    echo -e "   $SUMMARY_FILE"
    echo ""
    echo -e "${YELLOW}2. Plan Sprint $NEW_SPRINT:${NC}"
    echo -e "   - Run SCRUM-MASTER agent for sprint planning"
    echo -e "   - Update sprint goal in $NEW_SPRINT_DIR/planning/sprint-${NEW_SPRINT}-plan.md"
    echo -e "   - Review and prioritize backlog"
    echo ""
    echo -e "${YELLOW}3. Update PROJECT-STATE.md:${NC}"
    echo -e "   - Verify sprint number is correct"
    echo -e "   - Update sprint dates"
    echo -e "   - Set new sprint goal"
    echo ""
    echo -e "${YELLOW}4. Clean up state files:${NC}"
    echo -e "   - Review .claude/state/TASK-QUEUE.md"
    echo -e "   - Remove completed tasks"
    echo -e "   - Update priorities"
    echo ""
    echo -e "${YELLOW}5. Review archived content:${NC}"
    echo -e "   - Complete sprint summary with actual metrics"
    echo -e "   - Document lessons learned"
    echo -e "   - Identify technical debt"
    echo ""

    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║           READY TO START SPRINT $NEW_SPRINT!                        ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

# Run main function
main
